run_name: cfg
seed: 42
data_dir: ../imagenet100_128x128/train
image_size: 128
batch_size: 32
num_workers: 8
num_classes: 100
num_epochs: 50
learning_rate: 1e-4
weight_decay: 1e-5
num_train_timesteps: 1000
num_inference_steps: 20
beta_start: 0.0001
beta_end: 0.02
beta_schedule: linear

variance_type: fixed_small
prediction_type: epsilon
clip_sample: true
clip_sample_range: 1.0

unet_in_size: 128
unet_in_ch: 3
unet_ch: 128
unet_num_res_blocks: 2
unet_ch_mult: [1, 2, 2, 4]
unet_attn: [2, 3]
unet_dropout: 0.0

cfg_guidance_scale: 2.0

latent_ddpm: true
use_ddim: true
use_cfg: true

mixed_precision: fp16
grad_clip: 1.0
output_dir: experiments